# Generated by Django 4.0.6 on 2022-08-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUserModel',
            fields=[
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('SRN', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('Role', models.CharField(max_length=10)),
                ('Institution_code', models.CharField(max_length=25)),
            ],
        ),
    ]
