# Generated by Django 4.0.6 on 2022-08-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusermodel',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
