# Generated by Django 4.0.6 on 2022-12-01 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_victimmodel_record_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victimmodel',
            name='record_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
